### ISSUE TITLE
Is Span supported in the header?

### ISSUE THREAD

**Issue by marufaytekin** [alexeyco/simpletable#11]
Hey Alex, 

Thanks for this great library.

I am having an issue adding Span to the header. Any idea what I am doing wrong? I posted the error and code below.

Regards,
Maruf

Error: 
``` GOPATH=/Users/m0a00v4/go #gosetup
/usr/local/Cellar/go/1.15.5/libexec/bin/go build -o /private/var/folders/wh/fnt_yh0n5mxfmttpjts9l9jc0000gp/T/___go_build_main_go__2_ /Users/m0a00v4/go/src/github.com/simpletable/_example/05-colorize/main.go #gosetup
/private/var/folders/wh/fnt_yh0n5mxfmttpjts9l9jc0000gp/T/___go_build_main_go__2_
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x10d2ca9]

goroutine 1 [running]:
github.com/alexeyco/simpletable.(*Table).prepareColumns(0xc0000de000)
        /Users/m0a00v4/go/src/github.com/alexeyco/simpletable/table.go:257 +0xb69
github.com/alexeyco/simpletable.(*Table).String(0xc0000de000, 0xc000092b60, 0xc0000ac040)
        /Users/m0a00v4/go/src/github.com/alexeyco/simpletable/table.go:34 +0xdc
github.com/alexeyco/simpletable.(*Table).Println(0xc0000de000)
        /Users/m0a00v4/go/src/github.com/alexeyco/simpletable/table.go:65 +0x2f
main.main()
        /Users/m0a00v4/go/src/github.com/simpletable/_example/05-colorize/main.go:47 +0x97f

Process finished with exit code 2
```

Code:

```
func main() {
	table := simpletable.New()

	table.Header = &simpletable.Header{
		Cells: []*simpletable.Cell{
			{Align: simpletable.AlignCenter, Text: "FOO"},
			{Align: simpletable.AlignCenter, Text: "BAZ"},
			{Align: simpletable.AlignRight, Span: 2, Text: "BAR"},
		},
	}

	table.Body = &simpletable.Body{
		Cells: [][]*simpletable.Cell{
			{
				&simpletable.Cell{Text: red("I am red")},
				&simpletable.Cell{Text: green("I am green")},
				&simpletable.Cell{Text: blue("I am blue")},
				&simpletable.Cell{Text: blue("I am blue 2")},

			},
		},
	}

	table.Footer = &simpletable.Footer{
		Cells: []*simpletable.Cell{
			{Align: simpletable.AlignCenter, Span: 4, Text: gray("And all columns is well sized")},
		},
	}

	table.Println()
} 
```

**Comment by alexeyco** [comment]
Thanks, I'll do it next weekend
